### PR TITLE
add lifelines content

### PR DESCRIPTION
**Pull request by kcarini**

### CODE REVIEW

**Comment by kcarini** [comment]
not sure what is going on @danielfdsilva - its not letting me preview my changes either.

**Review by danielfdsilva — COMMENTED** [review]
@kcarini Could we use friendlier links to direct people elsewhere?
Instead of "something something here". More like "you can learn more at the something webiste", and link that?

**Comment by kcarini** [comment]
Thanks for calling me out for being lazy @danielfdsilva 😜 - I had just copy/pasted the text that was provided. I updated the sentences to be more in line with sharing links the way you described.

**Review by danielfdsilva — APPROVED** [review]
fantastic!

**Pull request merged**
